version: '3.7'

services:
  redis:
    image: redis:7
    container_name: youtube_redis

  youtube:
    image: youtube_image
    build:
      context: .
    container_name: youtube_app
    env_file:
      - .env
    depends_on:
      - redis
    ports:
      - 9000:8000